version: "3.8"

services:
  database:
    image: mysql:8.0.33
    container_name: database
    restart: unless-stopped
    env_file: .env
    environment:
      MYSQL_USER: "${MYSQLDB_USER}"
      MYSQL_ROOT_PASSWORD: "${MYSQLDB_ROOT_PASSWORD}"
      MYSQL_PASSWORD: "${MYSQLDB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQLDB_DATABASE}"
    ports:
      - "${MYSQLDB_LOCAL_PORT}:${MYSQLDB_DOCKER_PORT}"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${MYSQLDB_USER}" ]
      interval: 30s
      timeout: 30s
      retries: 5

  app:
    image: book_store
    container_name: book_store
    depends_on:
      - database
    restart: on-failure
    build: .
    env_file: .env
    ports:
      - "${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}"
      - "${DEBUG_PORT}:${DEBUG_PORT}"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://database:${MYSQLDB_DOCKER_PORT}/${MYSQLDB_DATABASE}"
      SPRING_DATASOURCE_USERNAME: ${MYSQLDB_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQLDB_ROOT_PASSWORD}
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: "org.hibernate.dialect.MySQLDialect"
      SPRING_JPA_DRIVER_CLASS_NAME: "com.mysql.cj.jdbc.Driver"
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"

