CREATE DATABASE IF NOT EXISTS ${MYSQLDB_DATABASE};
CREATE USER IF NOT EXISTS '${MYSQLDB_USER}'@'%' IDENTIFIED BY ${MYSQLDB_ROOT_PASSWORD};
GRANT ALL PRIVILEGES ON ${MYSQLDB_DATABASE}.* TO '${MYSQLDB_USER}'@'%';
FLUSH PRIVILEGES;
